

"use client"

import { Navigation } from '@/components/navigation'
import Link from 'next/link'
import Image from 'next/image'
import { useTheme } from 'next-themes'

export default function MentalHealthDisclaimer() {
  const { theme } = useTheme()
  
  return (
    <div className="min-h-screen bg-bg">
      <Navigation />
      {/* Main Content with Top Margin */}
      <div className="max-w-4xl mx-auto px-4 sm:px-6 pt-16 sm:pt-20 lg:pt-24 pb-8 sm:pb-10 lg:pb-12">
        <div>
          {/* Content */}
          <div className="prose prose-sm sm:prose-base max-w-none">
            <div className="space-y-6">
              <section>
                <p className="text-muted leading-relaxed mb-6">
                  At FitCommit, your physical and mental well-being are both important to us. While our application is designed to provide motivational tools that help users stay on track with their health and fitness goals, it is important to understand the limitations of our technology and the nature of the services provided.
                </p>
              </section>

              <section>
                <h2 id="ai-generated-results" className="font-epilogue text-text font-bold text-lg sm:text-xl tracking-tight mb-4" style={{ letterSpacing: '-0.02em' }}>
                  1. AI-Generated Results Are Estimates
                </h2>
                <p className="text-muted leading-relaxed mb-4">
                  FitCommit uses artificial intelligence to estimate body fat percentage and visualize potential physical progress based on user-submitted images and data. These results:
                </p>
                <ul className="text-muted leading-relaxed space-y-2 ml-6">
                  <li>Are generated by algorithms, not humans or healthcare professionals.</li>
                  <li>Are influenced by variables such as lighting, body position, image quality, and model training data.</li>
                  <li>Are approximations only, and may not accurately reflect your actual physical condition.</li>
                </ul>
                <p className="text-muted leading-relaxed mt-4">
                  You should not rely on these outputs as a definitive health diagnosis or scientific measurement.
                </p>
              </section>

              <section>
                <h2 id="not-medical-advice" className="font-epilogue text-text font-bold text-lg sm:text-xl tracking-tight mb-4" style={{ letterSpacing: '-0.02em' }}>
                  2. This Is Not Medical Advice
                </h2>
                <p className="text-muted leading-relaxed mb-4">
                  The FitCommit platform and all associated outputs (including body fat estimates and progress visualizations) are for informational and motivational purposes only.
                </p>
                <ul className="text-muted leading-relaxed space-y-2 ml-6">
                  <li>FitCommit is not a healthcare provider.</li>
                  <li>We do not offer diagnosis, treatment plans, or medical advice.</li>
                  <li>Any information provided by our app should not be used to make decisions about medical or mental health care.</li>
                </ul>
                <p className="text-muted leading-relaxed mt-4">
                  Always consult a qualified healthcare or mental health professional before making any health-related decisions based on app data.
                </p>
              </section>

              <section>
                <h2 id="mental-health-considerations" className="font-epilogue text-text font-bold text-lg sm:text-xl tracking-tight mb-4" style={{ letterSpacing: '-0.02em' }}>
                  3. Mental Health Considerations
                </h2>
                <p className="text-muted leading-relaxed mb-4">
                  We understand that body image and fitness progress can be emotionally sensitive subjects. Our app is designed to motivate, not to judge or create pressure.
                </p>
                <p className="text-muted leading-relaxed mb-4">
                  That said:
                </p>
                <ul className="text-muted leading-relaxed space-y-2 ml-6">
                  <li>FitCommit does not monitor or assess emotional well-being.</li>
                  <li>If you experience distress, anxiety, negative self-image, or unhealthy behaviors in relation to your body or fitness journey, we strongly encourage you to speak with a licensed mental health professional.</li>
                  <li>If you or someone you know is struggling, please seek immediate support from a counselor, therapist, or emergency mental health service.</li>
                </ul>
              </section>

              <section>
                <h2 id="user-responsibility" className="font-epilogue text-text font-bold text-lg sm:text-xl tracking-tight mb-4" style={{ letterSpacing: '-0.02em' }}>
                  4. User Responsibility
                </h2>
                <p className="text-muted leading-relaxed mb-4">
                  By using FitCommit, you acknowledge that:
                </p>
                <ul className="text-muted leading-relaxed space-y-2 ml-6">
                  <li>You are solely responsible for how you interpret and act upon the information presented in the app.</li>
                  <li>You will not use FitCommit to make medical or mental health decisions without first consulting a professional.</li>
                  <li>You understand that AI-generated data is fallible and not a substitute for clinical assessments or personal reflection.</li>
                </ul>
              </section>

              <section>
                <h2 id="limitations-technology" className="font-epilogue text-text font-bold text-lg sm:text-xl tracking-tight mb-4" style={{ letterSpacing: '-0.02em' }}>
                  5. Limitations of Technology
                </h2>
                <p className="text-muted leading-relaxed mb-4">
                  Our AI technology is evolving and subject to inherent limitations:
                </p>
                <ul className="text-muted leading-relaxed space-y-2 ml-6">
                  <li>It may occasionally produce inaccurate or biased results.</li>
                  <li>It cannot take into account complex physical or psychological factors.</li>
                  <li>It is not capable of understanding context, emotion, or lived experience.</li>
                </ul>
                <p className="text-muted leading-relaxed mt-4">
                  We continually improve our models, but users should maintain realistic expectations and use FitCommit as a supportive tool—not a sole authority.
                </p>
              </section>

              <section>
                <h2 id="contact-support" className="font-epilogue text-text font-bold text-lg sm:text-xl tracking-tight mb-4" style={{ letterSpacing: '-0.02em' }}>
                  6. Contact and Support
                </h2>
                <p className="text-muted leading-relaxed mb-4">
                  If you have concerns about your mental health or would like clarification about how our system works, please reach out to us.
                </p>
                <div className="text-muted leading-relaxed space-y-2">
                  <p><strong>Contact:</strong> <a href="mailto:hello@fitcommit.ai" className="text-accent hover:text-accent/80">hello@fitcommit.ai</a></p>
                  <div>
                    <p><strong>Mailing Address:</strong></p>
                    <p className="ml-4">
                      FitCommit Ltd.<br />
                      611 South Dupont Highway, Suite 102<br />
                      Dover, Delaware 19901<br />
                      USA
                    </p>
                  </div>
                </div>
              </section>
            </div>
          </div>
        </div>
      </div>

      {/* Footer */}
      <footer className="bg-surface border-t border-border py-8 sm:py-12 px-4 sm:px-6 lg:px-8">
        <div className="max-w-7xl mx-auto">
          {/* Mobile Layout */}
          <div className="block md:hidden">
            {/* Logo and Description */}
            <div className="text-center mb-8">
              <div className="flex justify-center mb-4">
                <Image
                  src={theme === 'dark' ? "/images/FitCommitLogoWebsiteLightLogo.svg" : "/images/FitCommitLogoWebsite.svg"}
                  alt="FitCommit Logo"
                  width={120}
                  height={120}
                  className="w-30 h-30 object-contain"
                />
              </div>
              <p className="text-muted text-sm mb-6 " style={{ marginTop: '-10px' }}>
                See your commitment. AI body fat percent from 3 photos. Your After Photo updates as you do.
              </p>
              
              {/* Legal Links - Mobile */}
              <div className="flex flex-wrap justify-center gap-4 mb-6">
                <Link href="/privacy" className="text-muted hover:text-accent transition-colors duration-200 text-sm">
                  Privacy Policy
                </Link>
                <Link href="/terms" className="text-muted hover:text-accent transition-colors duration-200 text-sm">
                  Terms of Service
                </Link>
                <Link href="/mental-health" className="text-muted hover:text-accent transition-colors duration-200 text-sm">
                  Mental Health
                </Link>
              </div>
            </div>

            {/* Mobile Links Grid */}
            <div className="grid grid-cols-2 gap-6 mb-8">
              <div>
                <h3 className="font-semibold text-text mb-3 text-sm">Product</h3>
                <ul className="space-y-2">
                  <li><a href="/#features" className="text-muted hover:text-accent transition-colors duration-200 text-sm">Features</a></li>
                  <li><a href="/#results" className="text-muted hover:text-accent transition-colors duration-200 text-sm">Results</a></li>
                  <li><a href="/#download" className="text-muted hover:text-accent transition-colors duration-200 text-sm">Download</a></li>
                </ul>
              </div>
              <div>
                <h3 className="font-semibold text-text mb-3 text-sm">Company</h3>
                <ul className="space-y-2">
                  <li><a href="/#team" className="text-muted hover:text-accent transition-colors duration-200 text-sm">Team</a></li>
                  <li><a href="/#faq" className="text-muted hover:text-accent transition-colors duration-200 text-sm">FAQ</a></li>
                  <li><a href="mailto:support@fitcommit.com" className="text-muted hover:text-accent transition-colors duration-200 text-sm">Support</a></li>
                  <li><a href="mailto:hello@fitcommit.com" className="text-muted hover:text-accent transition-colors duration-200 text-sm">Contact</a></li>
                </ul>
              </div>
            </div>
          </div>

          {/* Desktop Layout */}
          <div className="hidden md:grid md:grid-cols-4 gap-8">
            {/* Company Info */}
            <div className="col-span-1 md:col-span-2">
              <div className="flex items-center -mb-0 -mt-20">
                <Image
                  src={theme === 'dark' ? "/images/FitCommitLogoWebsiteLightLogo.svg" : "/images/FitCommitLogoWebsite.svg"}
                  alt="FitCommit Logo"
                  width={192}
                  height={192}
                  className="w-48 h-48 object-contain"
                />
              </div>
              <p className="text-muted mb-4 max-w-md">
                See your commitment. AI body fat percent from 3 photos. Your After Photo updates as you do.
              </p>
              <div className="flex space-x-4">
                <Link href="/privacy" className="text-muted hover:text-accent transition-colors duration-200">
                  Privacy Policy
                </Link>
                <Link href="/terms" className="text-muted hover:text-accent transition-colors duration-200">
                  Terms of Service
                </Link>
                <Link href="/mental-health" className="text-muted hover:text-accent transition-colors duration-200">
                  Mental Health
                </Link>
              </div>
            </div>

            {/* Quick Links */}
            <div>
              <h3 className="font-semibold text-text mb-4">Product</h3>
              <ul className="space-y-2">
                <li><a href="/#features" className="text-muted hover:text-accent transition-colors duration-200">Features</a></li>
                <li><a href="/#results" className="text-muted hover:text-accent transition-colors duration-200">Results</a></li>
                <li><a href="/#download" className="text-muted hover:text-accent transition-colors duration-200">Download</a></li>
              </ul>
            </div>

            {/* Company */}
            <div>
              <h3 className="font-semibold text-text mb-4">Company</h3>
              <ul className="space-y-2">
                <li><a href="/#team" className="text-muted hover:text-accent transition-colors duration-200">Team</a></li>
                <li><a href="/#faq" className="text-muted hover:text-accent transition-colors duration-200">FAQ</a></li>
                <li><a href="mailto:support@fitcommit.com" className="text-muted hover:text-accent transition-colors duration-200">Support</a></li>
                <li><a href="mailto:hello@fitcommit.com" className="text-muted hover:text-accent transition-colors duration-200">Contact</a></li>
              </ul>
            </div>
          </div>

          {/* Bottom Bar */}
          <div className="border-t border-border mt-6 sm:mt-8 pt-6 sm:pt-8 flex flex-col sm:flex-row justify-between items-center">
            <p className="text-muted text-sm text-center sm:text-left">
              Made with ❤️ <a href="https://epage.digital" target="_blank" rel="noopener noreferrer" className="hover:text-accent transition-colors duration-200">EPAGE DIGITAL</a>
            </p>
            <div className="flex space-x-6 mt-4 sm:mt-0">
              <a href="#" className="text-muted hover:text-accent transition-colors duration-200 text-sm">
                Twitter
              </a>
              <a href="#" className="text-muted hover:text-accent transition-colors duration-200 text-sm">
                LinkedIn
              </a>
              <a href="#" className="text-muted hover:text-accent transition-colors duration-200 text-sm">
                Instagram
              </a>
            </div>
          </div>
        </div>
      </footer>
    </div>
  )
}
